# Project Name
TARGET = EraseQspi

DEBUG = 1
OPT = -O0

# Sources
CPP_SOURCES = main.cpp

LIBDAISY_DIR = ../../libDaisy

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
